#!/bin/sh

function find_top_dir()
{
    local TOPDIR="poky"
# move into script file path
    cd $(dirname ${BASH_SOURCE[0]})

    if [ -d $TOPDIR ]; then
        echo $(pwd)
    else
        while [ ! -d $TOPDIR ] && [ $(pwd) != "/" ];
        do
             cd ..
        done

        if [ -d $TOPDIR ]; then
            echo $(pwd)
        else
            echo "/dev/null"
        fi
    fi
}

ROOT=$(find_top_dir)
echo ${ROOT}
export TEMPLATECONF=${ROOT}/poky/meta-jetson-customnux/meta-jetson-customnux-distro/conf/templates/jetson
export MACHINE="custom-jetson-orin-nano-devkit-nvme"
export DISTRO="default"
# dev
# release
phase="dev"

function build_target() {
    source ${ROOT}/poky/oe-init-build-env /media/sihokim/nvidia-poky/build-dashboard-jetson
    bitbake-layers add-layer /home/sihokim/projects/poky/meta-jetson-customnux/meta-jetson-customnux-dashboard

    if [ "$phase" = "dev" ]; then
        bitbake-layers add-layer /home/sihokim/projects/poky/meta-jetson-customnux/meta-jetson-customnux-dashboard-dev
    fi
}

build_target
